# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://sanchitsrivastava247@bitbucket.org/daffodilsoftware/bulbsharesdkpodspec.git'
#source 'https://sanchitsrivastava247@bitbucket.org/sanchitsrivastava247/newbulbshare.git'
target 'Bulbsdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BulbshareSDK'
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftLint'
  pod 'KeychainAccess'
  pod 'IQKeyboardManagerSwift'
  pod 'Koloda'
  pod 'MBProgressHUD'

  # Pods for Bulbsdk

end
